from stable_baselines3 import DQN, SAC, PPO
from models.custom_agents import DQN_F,  SAC_F, LimitedSAC, LimitedDQN

from ns_gym.schedulers import RandomScheduler

from environments.custom_update_functions import (
    BoundedDecrementUpdate,
)

from stable_baselines3.common.utils import LinearSchedule
from models.baselines import with_resets, with_l2_init


DQN_Reset = with_resets(DQN)
SAC_Reset = with_resets(SAC)

DQN_L2init = with_l2_init(DQN)
SAC_L2init = with_l2_init(SAC)


def get_tun_par(env_str, seed=0):
    if env_str == "ChooseBoxEnv-v0":
        tun_par = {"drift_timesteps" : [500_000, 1_000_000, 1_500_000]}
    elif env_str == "RiverSwim-v0": # Exploration
        tun_par = {}
    elif env_str == "MultiPadLunarLander":

        tun_par = {"drift_prob": 0.000008} 
             
    elif env_str == "CartPole-v1":
        scheduler = RandomScheduler(probability=0.00009, seed=seed)

        update_function = BoundedDecrementUpdate(scheduler=scheduler, k = 0.225, lo = 0.9)

        tun_par = {"force_mag": update_function}

    elif env_str == "MountainCarContinuous-v0":
        scheduler = RandomScheduler(probability=0.0002, seed=seed)

        update_function = BoundedDecrementUpdate(
           scheduler=scheduler, k=0.000015, lo=0.0004,
        )

        tun_par = {"power": update_function}

    elif env_str == "MountainCar-v0":
        scheduler = RandomScheduler(probability=0.0025, seed=seed)

        update_function = BoundedDecrementUpdate(
           scheduler=scheduler,  k= 0.000000125, lo=0.00075,
        )

        tun_par = {"force": update_function}

    elif env_str == "InvertedPendulum-v5":
        scheduler = RandomScheduler(probability=0.0004, seed=seed)  # 0.00006
        
        update_function = BoundedDecrementUpdate(scheduler=scheduler, k=0.0275, lo=0.5)


        tun_par = {"cart_mass": update_function}

    else:
        raise Exception("Parameter undefined for selected environment")
        

    return tun_par


experiment_settings = {
    # Cutom environments
    "ChooseBox": {
        "env_name": "ChooseBoxEnv-v0",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",
            "total_timesteps": 2000000,
        },
        "models": [PPO, DQN, DQN_F, DQN_Reset, DQN_L2init],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "n_steps": 128,
                "batch_size": 256,
                "n_epochs": 4,
                "gamma": 0.99,
                "gae_lambda": 0.95,
                "clip_range": 0.2,
                "clip_range_vf": 0.2,
                "normalize_advantage": True,
                "ent_coef": 0.01,
                "vf_coef": 0.5,
                "max_grad_norm": 0.5,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
            },
            { 
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.25,  # Default
                "baseline": 5,
                "world_model": "generated",
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
                "reset_interval": 400_000,
                "rewarm_epsilon": True,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
                "l2_lambda": 1e-5,
                "l2_anchor": "init",
            },
        ],
    },
    "MultiPadLLDiscrete": {
        "env_name": "MultiPadLunarLander",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",  # no need to wrap, already non-stationary
            "total_timesteps": 2000000,
            "continuous": False,
        },
        "models": [LimitedDQN, DQN, DQN_F, DQN_Reset, DQN_L2init, PPO],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
                "max_training_steps": 200000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,
                "baseline": 0,
                "world_model": "env",
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
                "reset_interval": 100_000,
                "rewarm_epsilon": True,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
                "l2_lambda": 1e-4,
                "l2_anchor": "init",
            },
            {
                "policy": "MlpPolicy",
                "n_steps": 1024,
                "batch_size": 64,
                "gae_lambda": 0.98,
                "gamma": 0.999,
                "n_epochs": 4,
                "ent_coef": 0.01,
            },
        ],
    },
    "MultiPadLLContinuous": {
        "env_name": "MultiPadLunarLander",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",  # no need to wrap, already non-stationary
            "total_timesteps": 1000000,
            "continuous": True,
        },
        "models": [LimitedSAC, SAC, SAC_F, SAC_Reset, SAC_L2init, PPO],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=3.65e-4, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
                "max_training_steps": 250000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=3.65e-4, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=3.65e-4, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,
                "baseline": -50,
                "world_model": "env",
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=3.65e-4, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
                "reset_interval": 200_000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=3.65e-4, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
                "l2_lambda": 1e-4,
                "l2_anchor": "init",
            },
            {
                "policy": "MlpPolicy",
                "n_steps": 1024,
                "batch_size": 64,
                "gae_lambda": 0.98,
                "gamma": 0.999,
                "n_epochs": 4,
                "ent_coef": 0.01,
            },
        ],
    },
   
    # DQN Classic Control
    "CartPole": {
        "env_name": "CartPole-v1",
        "env_settings": {
            "num_iterations": 10,
            "type": "classic",
            "total_timesteps": 1000000,
        },
        "models": [LimitedDQN, DQN, DQN_F, DQN_Reset, DQN_L2init, PPO],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
                "max_training_steps": 200000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,  
                "baseline": 0,
                "world_model": "env",
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_fraction": 0.16,
                "exploration_final_eps": 0.05,
                "verbose": 0,
                "reset_interval": 100_000,
                "rewarm_epsilon": True,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
                "l2_lambda": 1e-5,
                "l2_anchor": "init",
            },
            {
                "policy": "MlpPolicy",
                "n_steps": 32,
                "batch_size": 256,
                "gae_lambda": 0.8,
                "gamma": 0.98,
                "n_epochs": 20,
                "ent_coef": 0.0,
                "learning_rate": LinearSchedule(start=0.001, end=0, end_fraction=1),
                "clip_range": LinearSchedule(start=0.2, end=0, end_fraction=1),
                "n_envs": 1,
            },
        ],
    },
    "MountainCar": {
        "env_name": "MountainCar-v0",
        "env_settings": {
            "num_iterations": 10,
            "type": "classic",
            "total_timesteps": 1000000,
        },
        "models": [LimitedDQN, DQN, DQN_F, DQN_Reset, DQN_L2init, PPO],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "exploration_fraction": 0.2,
                "verbose": 0,
                "max_training_steps": 200000,
            },
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "exploration_fraction": 0.2,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "exploration_fraction": 0.2,
                "verbose": 0,
                "forget_ratio": 0.05,
                "eta_forgetting": 0.0015,
                "baseline": 0,
                "world_model": "env",   
            },
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "exploration_fraction": 0.2,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "verbose": 0,
                "reset_interval": 100_000,
                "rewarm_epsilon": True,
            },
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "exploration_fraction": 0.2,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "verbose": 0,
                "l2_lambda": 1e-4,
                "l2_anchor": "init",
            },
            {
                "normalize": True,
                "policy": "MlpPolicy",
                "n_steps": 16,
                "n_envs": 1,
                "gae_lambda": 0.98,
                "gamma": 0.99,
                "n_epochs": 4,
                "ent_coef": 0.0,
            },
        ],
    },
    
    
    # SAC Mujoco
    "InvertedPendulum": {
        "env_name": "InvertedPendulum-v5",
        "env_settings": {
            "total_timesteps": 1000000,
            "num_iterations": 10,
            "type": "mujoco",
        },
        "models": [LimitedSAC, SAC, SAC_F, SAC_Reset, SAC_L2init, PPO],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "buffer_size": 10000,
                "verbose": 0,
                "max_training_steps": 100000, 
            },
            {
                "policy": "MlpPolicy",
                "buffer_size": 10000,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "eta_forgetting": 0.0015,
                "forget_ratio": 0.25,
                "baseline": 0,
                "buffer_size": 10000,
                "verbose": 0,
                "world_model": "env",
            },
            {
                "policy": "MlpPolicy",
                "buffer_size": 10000,
                "verbose": 0,
                "reset_interval": 200_000,
                "rewarm_epsilon": True,
            },
            {
                "policy": "MlpPolicy",
                "buffer_size": 10000,
                "verbose": 0,
                "l2_lambda": 1e-5,
                "l2_anchor": "init",
            },
            {
                "normalize": True,
                "n_envs": 1,
                "policy": "MlpPolicy",
                "batch_size": 64,
                "n_steps": 32,
                "gamma": 0.999,
                "learning_rate": 0.000222425,
                "ent_coef": 1.37976e-07,
                "clip_range": 0.4,
                "n_epochs": 5,
                "gae_lambda": 0.9,
                "max_grad_norm": 0.3,
                "vf_coef": 0.19816,
            },
        ],
    },

    # Hard exploration
    "MountainCarContinuousNoSDE": {
        "env_name": "MountainCarContinuous-v0",
        "env_settings": {
            "total_timesteps": 100000,
            "num_iterations": 10,
            "type": "classic",
            "drift_disabled": True, # Only test exploration
        },
        "models": [PPO, SAC, SAC_F],
        "configurations": [
            {
                "normalize": True,
                "n_envs": 1,
                "policy": "MlpPolicy",
                "batch_size": 256,
                "n_steps": 8,
                "gamma": 0.9999,
                "learning_rate": 7.77e-05,
                "ent_coef": 0.00429,
                "clip_range": 0.1,
                "n_epochs": 10,
                "gae_lambda": 0.9,
                "max_grad_norm": 5,
                "vf_coef": 0.19,
                "use_sde": True,
                "policy_kwargs": dict(log_std_init=-3.29, ortho_init=False),
            },
            {
                "policy": "MlpPolicy",
                "buffer_size": 25000,
                "verbose": 0,
                "batch_size": 512,
                "train_freq": 32,
                "gradient_steps": 32,
                "gamma": 0.9999,
                "tau": 0.01,
                "use_sde": False,
            },
            {
                "policy": "MlpPolicy",
                "eta_forgetting": LinearSchedule(start=0.15, end=0, end_fraction=0.5),
                "forget_ratio": LinearSchedule(start=0.25, end=0, end_fraction=0.5),
                "buffer_size": 25000,
                "verbose": 0,
                "batch_size": 512,
                "train_freq": 32,
                "gradient_steps": 32,
                "gamma": 0.9999,
                "tau": 0.01,
                "use_sde": False,
                "world_model": "env",
                "baseline": 100,
            },
        ],
    },
    "RiverSwim": {
        "env_name": "RiverSwim-v0",
        "env_settings": {
            "num_iterations": 10,
            "type": "river",
            "total_timesteps": 10000,
        },
        "models": [DQN, PPO, DQN_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "gamma": 0.99,
                "target_update_interval": 20,
                "learning_rate": 1e-3,
                "batch_size": 64,
                "buffer_size": 50_000,
                "train_freq": 1,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.33,
                "exploration_initial_eps": 1,
                "verbose": 0,
            },
            {
                "normalize": True,
                "policy": "MlpPolicy",
                "n_steps": 32,
                "batch_size": 256,
                "gae_lambda": 0.8,
                "gamma": 0.98,
                "n_epochs": 20,
                "ent_coef": 0.0,
                "learning_rate": LinearSchedule(start=0.01, end=0, end_fraction=1),
                "clip_range": LinearSchedule(start=0.2, end=0, end_fraction=1),
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "gamma": 0.99,
                "target_update_interval": 20,
                "learning_rate": 1e-3,
                "batch_size": 64,
                "buffer_size": 50_000,
                "train_freq": 1,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.33,
                "exploration_initial_eps": 1,
                "verbose": 0,
                "eta_forgetting": 0.25,
                "forget_ratio": LinearSchedule(1, 0, 0.25),  # Default
                "baseline": 5000,
                "world_model": "env",
            },
        ],
    },

    # No-drift variants (base + F models only)
    "MultiPadLLDiscreteNoDrift": {
        "env_name": "MultiPadLunarLander",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",  # no need to wrap, already non-stationary
            "total_timesteps": 2000000,
            "continuous": False,
            "drift_disabled": True,
        },
        "models": [DQN, DQN_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 6.3e-4,
                "batch_size": 128,
                "buffer_size": 50000,
                "gamma": 0.99,
                "learning_starts": 0,
                "target_update_interval": 250,
                "train_freq": 4,
                "gradient_steps": -1,
                "exploration_final_eps": 0.1,
                "exploration_fraction": 0.12,
                "verbose": 0,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,
                "baseline": 0,
                "world_model": "env",
            },
        ],
    },
    "MultiPadLLContinuousNoDrift": {
        "env_name": "MultiPadLunarLander",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",  # no need to wrap, already non-stationary
            "total_timesteps": 2000000,
            "continuous": True,
            "drift_disabled": True,
        },
        "models": [SAC, SAC_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=0, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[400, 300]),
                "batch_size": 256,
                "learning_rate": LinearSchedule(start=7.3e-4, end=0, end_fraction=1),
                "buffer_size": 1000000,
                "ent_coef": "auto",
                "gamma": 0.99,
                "tau": 0.01,
                "train_freq": 1,
                "gradient_steps": 1,
                "learning_starts": 10000,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,
                "baseline": -50,
                "world_model": "env",
            },
        ],
    },
    "MountainCarNoDrift": {
        "env_name": "MountainCar-v0",
        "env_settings": {
            "num_iterations": 10,
            "type": "classic",
            "total_timesteps": 1000000,
            "drift_disabled": True,
        },
        "models": [DQN, DQN_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "exploration_fraction": 0.2,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "learning_rate": 4e-3,
                "batch_size": 128,
                "buffer_size": 10000,
                "gamma": 0.98,
                "target_update_interval": 600,
                "train_freq": 16,
                "gradient_steps": 8,
                "exploration_final_eps": 0.07,
                "policy_kwargs": dict(net_arch=[256, 256]),
                "exploration_fraction": 0.2,
                "verbose": 0,
                "forget_ratio": 0.05,
                "eta_forgetting": 0.0015,
                "baseline": 0,
                "world_model": "env",   
            },
        ],
    },
    "CartPoleNoDrift": {
        "env_name": "CartPole-v1",
        "env_settings": {
            "num_iterations": 10,
            "type": "classic",
            "total_timesteps": 1000000,
            "drift_disabled": True,
        },
        "models": [DQN, DQN_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[256, 256]),
                "learning_rate": 2.3e-3,
                "batch_size": 64,
                "buffer_size": 100000,
                "target_update_interval": 10,
                "train_freq": 256,
                "gradient_steps": 128,
                "exploration_initial_eps": 0.95,
                "gamma": 0.995,
                "exploration_final_eps": 0.05,
                "exploration_fraction": 0.16,
                "verbose": 0,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.05,  # Default
                "baseline": 0,
                "world_model": "env",
            },
        ],
    },
    "ChooseBoxNoDrift": {
        "env_name": "ChooseBoxEnv-v0",
        "env_settings": {
            "num_iterations": 10,
            "type": "none",
            "total_timesteps": 2000000,
            "drift_disabled": True,
        },
        "models": [DQN, DQN_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
            },
            { # Works well!
                "policy": "MlpPolicy",
                "policy_kwargs": dict(net_arch=[64, 64]),
                "target_update_interval": 20,
                "n_steps": 3,
                "exploration_fraction": 0.5,
                "gamma": 0.95,
                "batch_size": 64,
                "train_freq": 1,
                "eta_forgetting": 0.015,
                "forget_ratio": 0.25,  # Default
                "baseline": 5,
                "world_model": "generated",
            },
        ],
    },
    "InvertedPendulumNoDrift": {
        "env_name": "InvertedPendulum-v5",
        "env_settings": {
            "total_timesteps": 1000000,
            "num_iterations": 10,
            "type": "mujoco",
            "drift_disabled": True,
        },
        "models": [SAC, SAC_F],
        "configurations": [
            {
                "policy": "MlpPolicy",
                "buffer_size": 10000,
                "verbose": 0,
            },
            {
                "policy": "MlpPolicy",
                "eta_forgetting": 0.0015,
                "forget_ratio": 0.25,
                "baseline": 0,
                "buffer_size": 10000,
                "verbose": 0,
                "world_model": "env",
            },
        ],
    },
}
